### ISSUE TITLE
Interoperabilität: Spezifizierung von personenbezogenen Daten

### ISSUE THREAD

**Issue by the-infinity** [ridesharing-api/documentation#11]
Es ergibt Sinn, auch personenbezogene Daten zu spezifizieren, da es durchaus Anwendungsfälle gibt, wo personenbezogene Daten Sinn ergeben oder sogar zwingende Voraussetzung sind. Beispiele wären Mitfahr-Portal-Zusammenarbeiten oder Austausch / Download von personenbezogenen Daten seitens des Nutzers. Es wäre hilfreich, dort auch eine Vorlage zu haben. Die Daten dürften jedoch nie in das Metaportal gebracht werden.

**Comment by c-rath** [comment]
Für die Kooperation von Mitfahrzentralen oder Ride-Sharing-Anbietern ist es zwingend notwendig, dass sie für den Service notwendige Kontaktdaten GRPR-kompatibel austauschen können, die eine Kontaktaufnahme ermöglichen. In der Regel sind das Name, Telefonnummer und Email-Adresse. Für Telefon und Email könnte man einen Proxy-Service einrichten, der diese Daten maskiert bzw. Kontakte anonymisiert weiterleitet.

**Comment by the-infinity** [comment]
Die personenbezogenen Daten sind in https://github.com/ridesharing-api/documentation/blob/master/schema/Person.json sowie https://github.com/ridesharing-api/documentation/blob/master/schema/PersonContact.json mittlerweile drin, so dass ein Datenformat dafür feststeht. Wie diese transportiert werden ist allerdings out of scope: das wäre etwas, was ein Metaportal leisten könnte (aber nicht muss - das geht ja auch schlicht als JSON Export).

**Comment by the-infinity** [comment]
Personenbezogene Daten zum Export sind in der aktuellen Fassung enthalten.
