### ISSUE TITLE
Anwendungsfälle der API

### ISSUE THREAD

**Issue by hbruch** [ridesharing-api/documentation#3]
Eine standardisierte API ist aus meiner Sicht für eine Reihe von Anwendungsfällen sinnvoll. Je nach Anwendungsfalls ergeben sich nochmal verschiedene Anforderungen. 
Daher sollten die intendierten Anwendungsfälle explizit in der Dokumentation beschrieben werden.

Aus meiner Sicht sind dies:
* Datenübertragbarkeit gemäß Art. 20 DSGVO
* Datenabgabe an Metasuche
* API zur Inseratverwaltung durch Endnutzer

**Comment by the-infinity** [comment]
Erste Version mit https://github.com/ridesharing-api/documentation/commit/c5d5da0a39afcbff2d916778a7d7ab77b3617d60 .

**Comment by c-rath** [comment]
Sieht so etwa der angedachte Standard-Anwendungsfall aus?
1) Mitfahr-Portale möchten mehr Nutzer auf ihr System bringen und füttern dazu das MetaMitfahrPortal mit ihren Daten.
2) Pot. Mitfahrer möchten effizient suchen und geben ihre Anfrage in MMP statt auf den Systemen der einzelnen Anbieter ein.
3) Im Falle von Treffern erhält der Mitfahrer eine Liste der Treffer mit URLs zu den jeweiligen Anbietern, möglichst mit Übergabe der Buchungsdaten der jeweiligen Fahrt.
4) Die Buchung erfolgt auf den Seiten der jeweiligen Anbieter.

**Comment by the-infinity** [comment]
Es wurden mehrere Anwendungsfälle beschrieben.
