### ISSUE TITLE
Datenmodell als UML-Modell

### ISSUE THREAD

**Issue by hbruch** [ridesharing-api/documentation#4]
Abschnitt 2.9 beinhaltet eine graphische Darstellung der Ridesharing.API-Objekte.
Dies ist bereits hilfreich.

Ich schlage vor, an dieser Stelle ein UML-Modell zu verwenden, aus dem Vererbungsbeziehungen, Kardinalitäten und (ggf. in einer zweiten Detaildarstellung) auch Attribute hervorgehen.

**Comment by the-infinity** [comment]
Erster Vorschlag in https://github.com/ridesharing-api/documentation/commit/c14f28833e84e63d1e6e445d5e06f7bba6571ef0 . Mit eingearbeitet: diverse Vorschläge aus dem Workshop.

**Comment by the-infinity** [comment]
Das UML-Modell wurde umgesetzt und liegt im Repository.
